### ISSUE TITLE
Can not generate deobfuscated jar for newest snapshot: ExecutionException

### ISSUE THREAD

**Issue by Bixilon** [HeartPattern/MC-Remapper#16]
Hey, getting a crash:

```
oritz@moritz-tp:~/Games/Minecraft/MC-Remapper/build/install/MC-Remapper/bin$ ./MC-Remapper client 21w15a
Download input
Exception in thread "main" java.util.concurrent.ExecutionException: kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 2289: Encountered an unknown key javaVersion
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
        at io.heartpattern.mcremapper.commandline.MCRemapperApp$versionInfo$2.invoke(MCRemapperApp.kt:73)
        at io.heartpattern.mcremapper.commandline.MCRemapperApp$versionInfo$2.invoke(MCRemapperApp.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.heartpattern.mcremapper.commandline.MCRemapperApp.getVersionInfo(MCRemapperApp.kt)
        at io.heartpattern.mcremapper.commandline.MCRemapperApp.run(MCRemapperApp.kt:81)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at io.heartpattern.mcremapper.commandline.MCRemapperAppKt.main(MCRemapperApp.kt:187)
Caused by: kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 2289: Encountered an unknown key javaVersion
        at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:293)
        at kotlinx.serialization.json.internal.JsonReader.fail$default(JsonReader.kt:292)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeObjectIndex(StreamingJsonInput.kt:123)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeElementIndex(StreamingJsonInput.kt:88)
        at io.heartpattern.mcversions.model.Version$$serializer.deserialize(Version.kt)
        at io.heartpattern.mcversions.model.Version$$serializer.deserialize(Version.kt:14)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:34)
        at kotlinx.serialization.json.internal.StreamingJsonInput.decodeSerializableValue(StreamingJsonInput.kt:33)
        at kotlinx.serialization.CoreKt.decode(Core.kt:80)
        at kotlinx.serialization.json.Json.parse(Json.kt:126)
        at io.ktor.client.features.json.serializer.KotlinxSerializer.read(KotlinxSerializer.kt:76)
        at io.ktor.client.features.json.JsonFeature$Feature$install$2.invokeSuspend(JsonFeature.kt:107)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

Happens in newest snapshot, other versions not tested

Thanks

Moritz

**Comment by HeartPattern** [comment]
It was problem from MCVersions since new field "javaVersion" is added to Mojang's version information json.
Fixed on https://github.com/HeartPattern/MC-Remapper/commit/bce1c8b6698d805a08adb8e52d42b386382130c5
