### ISSUE TITLE
Compatible issue to the latest snapshot 21w19a

### ISSUE THREAD

**Issue by bilintsui** [HeartPattern/MC-Remapper#20]
As the title, when I deobfuscate the 21w19a client jar, it says: "Unsupported class file major version 60".
Maybe caused by Mojang increase the requirement of Minimum Java version?

Environment: WSL(Ubuntu 20.04.1 LTS) on Windows 10 20H2(19402.985), MC-Remapper(60d547).
Executed command line: `./MC-Remapper 21w19a_original.jar 21w19a_clientmap.txt --output-name 21w19a_deobf.jar`
Note: Client .jar file and Client map .jar file obtained using links from the Minecraft Wiki (21w19a).

Outputs:
<pre>
Download input
Download mapping
Parse mapping
Resolve super type
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 60
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
        at io.heartpattern.mcremapper.preprocess.SuperTypeResolver$Companion.fromFile(SuperTypeResolver.kt:26)
        at io.heartpattern.mcremapper.commandline.MCRemapperApp.run(MCRemapperApp.kt:112)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at io.heartpattern.mcremapper.commandline.MCRemapperAppKt.main(MCRemapperApp.kt:187)
</pre>

**Comment by bilintsui** [comment]
Append: Installed Java version: build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01.

**Comment by HeartPattern** [comment]
Error is occurred because latest minecraft is compiled with java 16.
Fixed in 702170dc013e9fe315b5fd5f01deb932e01c7035 with version 2.0.6-SNAPSHOT
